### ISSUE TITLE
A walkthrough would be marvelous

### ISSUE THREAD

**Issue by dfnr2** [kenrector/sigma-cpv-kit#3]
Thank you so much for sharing this project.  

Using the README, I was able to telnet in, but neither setting DEP 114a 0 or sending a BREAK seems to trigger a login prompt.

It would be really awesome if you were to capture a walkthrough of the set as a text file.

**Comment by dfnr2** [comment]
I was able to get the login prompt following the directions.  A walkthrough might still be nice, though.

**Comment by kenrector** [comment]
What did you do differently that allowed you to get logged in?

If you let me know I'll try to improve the documentation.

There are three things in the kit to help one log on.  The README, the 
cpcpdoc.txt file and a page in the WSLubunto WIKI page.
I hesitate to add another but I would appreciate comments about where 
these three documents are lacking.

Thanks for having a go at CP-V.

Ken

**Comment by dfnr2** [comment]
The WSLubuntu WIKI page walkthrough is perfect.  Any chance of adding that to the repo?

**Comment by kenrector** [comment]
I believe the WIKI page is part of the repository.

I believe that what you did differently to get logged on was explained in another issue.
