### ISSUE TITLE
Trouble getting the login prompt.

### ISSUE THREAD

**Issue by dfnr2** [kenrector/sigma-cpv-kit#5]
I have successfully built the sigma simulator, used the cpv-kit and logged in on two MacOS desktops (2019 Intel MacPro/big sur and 2009 Intel MacPro/mojave).  On my laptop (2019 Intel MacBook Pro/Big Sur), I can boot from tape and the operator console seems to be working.  After "!OPEN 107" and (in simh) "dep 114a 0", I can connect to the simulator.  I get:

`Connected to the XDS Sigma simulator MUX device, line 6`

But don't get a login prompt even if I send a BRK signal (telnet SEND BRK)

I am pretty sure I am doing all the same steps on all the systems.  Any suggestions?

**Comment by kenrector** [comment]
In issue #3, at about the same time as you entered this note you said:
"I was able to get the login prompt following the directions."
I assume you recognized that  OPEN 107 was incorrect and should have been ON 107.

I'm closing this issue.
