### ISSUE TITLE
unimplemented instruction running BASIC

### ISSUE THREAD

**Issue by dfnr2** [kenrector/sigma-cpv-kit#6]
Attempting to execute any basic commands (in a program or from the prompt) results in an "unimplemented instruction" trap. I suspect this in an emulation bug, but since you seem to be able to run BASIC programs, I am wondering if it's a simh config setting.

FORT, EDIT, and APL seem to be working fine.

```
!BASIC
VER. C02
>10 FOR I = 1 TO 10
>20 PRINT I
>30 NEXT I
>40 STOP
>50 END
>RUN
:P6   ^   RUNQAAA...
  A405 UNIMPLEMENTED INSTRUCTION

!
```

**Comment by kenrector** [comment]
You're right.
This code resulted in an FPA,10 a74e instruction.
The sigma.ini options should include a  set cpu FP to allow the floating point instructions
I added the change and committed sigma.ini
