### ISSUE TITLE
sigma.ini tries to use cpcp.tap from parent directory.

### ISSUE THREAD

**Issue by dfnr2** [kenrector/sigma-cpv-kit#7]
The sigma.ini file has the line:

`att mt0   ../cpcp.tap`

which looks for the cpcp.tap file in the parent directory.  This can work if the file is copied or linked to the parent, but as pulled from the repo, I have been removing the ../ to make it work.  I can imaging there could a reason for this, for example, to preserve the repo version if the tape image is being modified.

**Comment by kenrector** [comment]
You may put the PO tape file anywhere it suits you.  You are free to modify anything you like, at your own risk.

**Comment by dfnr2** [comment]
I agree.  But removing the '../' will allow the setup to boot unmodified when pulled fresh from the repository.

**Comment by kenrector** [comment]
OK.

I also added :
You may wish to modify this file, particularly the MT and DP attach commands to suit your personal environment.

to the readme

**Comment by kenrector** [comment]
see previous comment
